apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ib-interface-normalization
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: fab-rig
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/25b-ib-interface-normalization
    repoURL: https://github.com/srikantt/Infrabric-deployer.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 8
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
